### ISSUE TITLE
IWebElement.FindElement(By by) method can't take Selenium.WebDriver.Extentions.JQuerySelector

### ISSUE THREAD

**Issue by GLloydSC** [RaYell/selenium-webdriver-extensions#15]
I think the title says it all:

IWebDriver.FindElement(Selenium.WebDriver.Extentions.JQuerySelector by)  is ok
IWebElement.FindElement(Selenium.WebDriver.Extentions.JQuerySelector by) is not ok

**Comment by RaYell** [comment]
I've found a possible workaround that would allow to implement the similar behavior as invoking `FindElement`/`FindElements` on `IWebElement`.

The way this could work is I could add a wrapper type on `RemoteWebElement` (the base type implementing `IWebElement` interface) and on this wrapper store also information about the selector that has been used to locate it. Having this information it should be possible to generate a new selector taking into account that the scope for the new search has been narrowed by previous query.

**Comment by RaYell** [comment]
The functionality is implemened as part of the https://github.com/RaYell/selenium-webdriver-extensions/pull/21

It's scheduled to be released with version 1.2. It comes with several limitations which you can find in the pull request comments.
