### ISSUE TITLE
cannot convert from Selenium.WebDriver.Extensions.JQuery.JQuerySelector to OpenQA.Selenium.By

### ISSUE THREAD

**Issue by joelransom** [RaYell/selenium-webdriver-extensions#84]
I created a simple console project and installed the following. 
```
install-package selenium.webdriver
install-package selenium.webdriver.extensions
```

code: 
```
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using Selenium.WebDriver.Extensions;
using By = Selenium.WebDriver.Extensions.By;

namespace SeleniumWebDriverExtTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var driver = new FirefoxDriver();
            //driver.Navigate().GoToUrl("www.google.com");
            var foo = driver.FindElements(By.JQuerySelector("input:visible"));
        }
    }
}
```
I get the following errors on the By.JQuerySelector line

![image](https://cloud.githubusercontent.com/assets/3892731/7071590/1c7e8822-de9b-11e4-879e-0d348f85bafa.png)

Let me know if I've overlooked something basic.

**Comment by RaYell** [comment]
I think the problem might be with the `using Selenium.WebDriver.Extensions;` line. Can you replace it with
`using Selenium.WebDriver.Extensions.Core;`

If I'm right that this is the cause then it's related to an extension method being available only in `Core` namespace which is a bug that I intend to fix. I'm already working on a it but that may take few more days to complete and release a new version - you can check the progress in #83. Once this fix is done the extension methods should work with all of the `Selenium.WebDriver.Extensions*` namespaces. 

Please let me know if changing the `using` statement fixes the issue for you.

**Comment by joelransom** [comment]
Wow, that was fast, thanks!
Yes, that did work. I also needed to add Selenium.Support which I typically would have anyway.

**Comment by RaYell** [comment]
I'm glad that worked for you. Stay tuned for next release where this "hack" will not be required.
