### ISSUE TITLE
Support for page objects

### ISSUE THREAD

**Issue by yannisgu** [RaYell/selenium-webdriver-extensions#86]
Selenium knows the concept of [page objects](https://code.google.com/p/selenium/wiki/PageObjects). This allows to map an object to a HTML page. Each property of the class to map must be extended with the `FindsBy` attribute:
```C#
[FindsBy(How = How.CssSelector, Using = ".items .item")]
public IList<IWebElement> Items { get; set; } 
```

Would be cool if the jQuery selector could be used there to. In order to do this, it must inherit from `By` and implement it correctly. The code would then look like this:
```C#
[FindsBy(CustomFinderType = typeof(jQuerySelector), Using = ".items item"]
public IList<IWebElement> Items { get; set; } 
```

**Comment by RaYell** [comment]
I've added the support for Page Objects that will be released with V2 of the extensions library.

One important thing you need to keep in mind while using this feature that if you are using `CustomFinderType` you still need to provide `How` parameter, or it will not work. So in the example you've given the actual code would have to be:

```csharp
[FindsBy(How = How.Custom, CustomFinderType = typeof(jQuerySelector), Using = ".items item"]
public IList<IWebElement> Items { get; set; } 
```
