### ISSUE TITLE
Error Action

### ISSUE THREAD

**Issue by tablesmit** [RaYell/selenium-webdriver-extensions#90]
var element = WebDriverExtensions.FindElement(driver, Selenium.WebDriver.Extensions.By.Name(value))
Actions action = new Actions(driver);
action.ContextClick(element).Perform();

I'm get error.

Execute:
The IWebElement object must implement or wrap an element that implements ILocatable.
Parameter name: element

---------------------------------------------

System.ArgumentException: The IWebElement object must implement or wrap an element that implements ILocatable.
Parameter name: element
   at OpenQA.Selenium.Interactions.Actions.GetLocatableFromElement(IWebElement element)
   at OpenQA.Selenium.Interactions.Actions.ContextClick(IWebElement onElement)
   at Advanced_Selenium.WebDriveMouseClick.MouseAction(IWebDriver driver, IWebElement element, String clickType)

**Comment by RaYell** [comment]
The reason for that is that the `WebElement` returned by the extension method is not a full implementation of the Selenium's `RemoteWebElement` but rather a wrapper. There's a property on the extension's `WebElement` called `InnerElement` on which you'll be able to perform actions, however it's protected for now, but I'll expose it as a public member in one of the next release.
